import { BonusHistory } from '@business-entities';

export const MOCK_BONUS_HISTORY: BonusHistory[] = [
    {
        category: 'Рестораны',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Москва, ул. Тверская, 12',
        title: 'Гурман',
        discount: 10,
    },
    {
        category: 'Супермаркеты',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Санкт-Петербург, Невский пр., 24',
        title: 'Кешбэк за покупку в "Перекрёстке"',
        discount: 5,
    },
    {
        category: 'Кафе',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Казань, Баумана, 33',
        title: 'Арома',
        discount: 7,
    },
    {
        category: 'АЗС',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Новосибирск, Красный пр., 88',
        title: 'Роснефть',
        discount: 3,
    },
    {
        category: 'Аптеки',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Екатеринбург, Ленина, 9',
        title: 'Здоровье',
        discount: 8,
    },
    {
        category: 'Транспорт',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Москва, метро Арбатская',
        title: 'Метро',
        discount: 5,
    },
    {
        category: 'Отели',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Сочи, Курортный пр., 45',
        title: 'Novotel',
        discount: 12,
    },
    {
        category: 'Кинотеатры',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Москва, ул. Пушкинская, 11',
        title: 'Космопарк',
        discount: 10,
    },
    {
        category: 'Электроника',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Санкт-Петербург, Лиговский пр., 25',
        title: 'Mobile Store',
        discount: 6,
    },
    {
        category: 'Фитнес',
        date: '10 Мая 2024, 10:12',
        image: '/profile/profile.webp',
        location: 'Казань, ул. Спортивная, 7',
        title: 'JFC JYM',
        discount: 9,
    },
];
