import { ClientHistory } from '@business-entities';

export const MOCK_CLIENT_HISTORY: ClientHistory[] = [
    {
        image: '/auth.webp',
        title: 'Novotel',
        category: 'Отель',
        location: 'Бишкек, Кыргызстан',
        rating: 4.5,
        review_count: 32,
    },
    {
        image: '/auth.webp',
        title: 'Gourmet Palace',
        category: 'Ресторан',
        location: 'Алматы, Казахстан',
        rating: 4.8,
        review_count: 54,
    },
    {
        image: '/auth.webp',
        title: 'Coffee House',
        category: 'Кафе',
        location: 'Москва, Россия',
        rating: 4.6,
        review_count: 78,
    },
    {
        image: '/auth.webp',
        title: 'Art Museum',
        category: 'Музей',
        location: 'Санкт-Петербург, Россия',
        rating: 4.7,
        review_count: 90,
    },
    {
        image: '/auth.webp',
        title: 'Sky Bar',
        category: 'Бар',
        location: 'Дубай, ОАЭ',
        rating: 4.3,
        review_count: 45,
    },
    {
        image: '/auth.webp',
        title: 'Maldives Resort',
        category: 'Курорт',
        location: 'Мальдивы',
        rating: 4.9,
        review_count: 120,
    },
    {
        image: '/auth.webp',
        title: 'Luxury Spa',
        category: 'Спа',
        location: 'Бали, Индонезия',
        rating: 4.7,
        review_count: 60,
    },
    {
        image: '/auth.webp',
        title: 'Central Park',
        category: 'Парк',
        location: 'Нью-Йорк, США',
        rating: 4.8,
        review_count: 200,
    },
    {
        image: '/auth.webp',
        title: 'Grand Theater',
        category: 'Театр',
        location: 'Лондон, Великобритания',
        rating: 4.6,
        review_count: 85,
    },
    {
        image: '/auth.webp',
        title: 'Sunset Beach',
        category: 'Пляж',
        location: 'Майами, США',
        rating: 4.9,
        review_count: 150,
    },
];
