import { AnimationTracker, Layout } from '@components';

import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Raleway, Roboto } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import CollectedProviders from '@/providers/collected-providers';
import '../globals.css';

const raleway = Raleway({
	variable: '--font-raleway',
	subsets: ['latin', 'cyrillic'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['100', '300', '400', '500', '700', '900'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const { locale } = await params;

	return (
		<html lang={locale || 'ru'} suppressHydrationWarning>
			<body className={`${raleway.variable} ${roboto.variable} antialiased min-w-96`}>
				<NextTopLoader color="var(--yellow)" height={3} showSpinner={false} />
				<NextIntlClientProvider>
					<CollectedProviders>
						<Layout>{children}</Layout>
						<AnimationTracker />
					</CollectedProviders>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
