import { Layout } from '@components';
import { CollectedProviders } from '@providers';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Inter } from 'next/font/google';
import '../globals.css';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin', 'cyrillic'],
    weight: ['100', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const { locale } = await params;

    return (
        <html
            lang={locale || 'ru'}
            suppressHydrationWarning
        >
            <body className={`${inter.variable} antialiased`}>
                <NextIntlClientProvider>
                    <CollectedProviders>
                        <Layout>{children}</Layout>
                    </CollectedProviders>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
